version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code/
      - /code/node_modules
    environment:
      - PORT
    ports:
      - "${PORT}:${PORT}"
    command: yarn start:dev
